Add isMember & memberIcon to returned data
FreeTubeApp/yt-comment-scraper pull request #28
Opened 2021-08-18 02:27 UTC by ChunkyProgrammer

isMember will return true if the user is a paid member of the uploader's channel
memberIcon will return the url of the image that appears beside a member's name (if the user is a member)

2021-09-18 13:50 UTC, efb4f5ff-1298-471a-8973-3d47447115dc requested changes

2021-09-18 13:50 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented on README.md
> +      isMember: Boolean, // Whether the user that nade the comment is a paid member or not
made*

2021-09-18 13:50 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented on README.md
> +    isMember: Boolean, // Whether the user that nade the comment is a paid member or not
Same here

2021-09-21 01:49 UTC, PikachuEXE requested changes

2021-09-21 01:49 UTC, PikachuEXE commented on README.md
> +    memberIcon: String | null // URL of the member icon
I imagine `memberIcon` would be something like:
```js
memberIcon: {
  url: "URL",
  height: 100,
  width: 100,
  otherMetadata: "whatever",
}
```
Actually if you look at how you fetch the URL
`customBadge.thumbnails` is an array of objects not strings
```suggestion
    memberIconURL: String | null // URL of the member icon
```

2021-09-23 18:26 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
https://github.com/FreeTubeApp/yt-comment-scraper/pull/27#issuecomment-926050358

2021-09-24 23:02 UTC, PikachuEXE approved these changes

2021-09-24 23:03 UTC, PikachuEXE commented
@efb4f5ff-1298-471a-8973-3d47447115dc updated

2021-09-24 23:22 UTC, peepopoggers commented
Is Url more standard than URL?

2021-09-24 23:40 UTC, PikachuEXE commented
See `authorThumb`
There is already `url`
I think it's fine to use `Url` as **suffix**
If we insist on using `URL` in code the naming might look strange sometimes

2021-09-25 00:50 UTC, peepopoggers approved these changes

2021-09-25 05:56 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2021-09-25 05:56 UTC, merged