Add TypeScript definitions
FreeTubeApp/yt-comment-scraper pull request #35
Opened 2022-02-19 23:08 UTC by ChunkyProgrammer

2022-05-24 08:25 UTC, absidue submitted a review, later dismissed

2022-05-24 08:27 UTC, efb4f5ff-1298-471a-8973-3d47447115dc submitted a review, later dismissed

2022-05-24 09:30 UTC, PikachuEXE requested changes

2022-05-24 09:30 UTC, PikachuEXE commented on index.d.ts
> +}
Why no newline here even though [we have a rule in `.editorconfig`](https://github.com/FreeTubeApp/yt-comment-scraper/blob/development/.editorconfig#L9)

2022-05-28 02:01 UTC, PikachuEXE approved these changes

2022-05-28 06:46 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2022-05-29 19:45 UTC, absidue approved these changes

2022-05-29 19:45 UTC, merged