Add linting + update dependencies
FreeTubeApp/yt-comment-scraper pull request #44
Opened 2022-08-23 13:49 UTC by ChunkyProgrammer

closes #43

2022-08-23 14:12 UTC, ChunkyProgrammer commented
will open a pr to switch to named object parameters once this is merged

2022-08-23 15:23 UTC, efb4f5ff-1298-471a-8973-3d47447115dc submitted a review, later dismissed

2022-08-24 01:11 UTC, PikachuEXE requested changes

2022-08-24 01:11 UTC, PikachuEXE commented on .eslintrc.js
> +    'object-shorthand': 0
What do 0 & 1 mean...

2022-08-24 01:11 UTC, PikachuEXE commented on src/Youtube-Scraper.js
> +      if ('commentsHeaderRenderer' in headerElem) { total = Number(headerElem?.commentsHeaderRenderer?.countText?.runs?.[0]?.text?.replace(',', '')) ?? null }
Why isn't this considered as a long line?
```suggestion
      if ('commentsHeaderRenderer' in headerElem) { 
        total = Number(headerElem?.commentsHeaderRenderer?.countText?.runs?.[0]?.text?.replace(',', '')) ?? null
      }
```

2022-08-24 01:18 UTC, PikachuEXE requested changes
https://eslint.org/docs/latest/user-guide/configuring/rules#configuring-rules

No point making it harder to read later

2022-08-24 01:18 UTC, PikachuEXE commented on .eslintrc.js
> +    'object-shorthand': 0
```suggestion
    'space-before-function-paren': 'off',
    'comma-dangle': 'off',
    'no-console': 'off',
    'no-unused-vars': 'warn',
    'no-undef': 'warn',
    'object-shorthand': 'off'
```

2022-08-24 13:33 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2022-08-24 13:36 UTC, absidue approved these changes

2022-08-24 13:39 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
@PikachuEXE your health is low, we got to finish this battle fast. Use your ultimate thunder shock approval move now!!!

2022-08-24 13:49 UTC, PikachuEXE approved these changes
It's 9pm in my time zone man = =

2022-08-24 13:49 UTC, merged

2022-08-24 14:00 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Oops sorry about that its 4pm in mine